# Generated by Django 4.2.5 on 2023-10-03 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_opportunity_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='forum',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterModelOptions(
            name='opportunity',
            options={'ordering': ['name'], 'verbose_name_plural': 'Opportunities'},
        ),
        migrations.AlterModelOptions(
            name='waitlist',
            options={'ordering': ['-date_created']},
        ),
    ]
