# Generated by Django 4.2.5 on 2023-12-23 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_opportunity_name_alter_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_forums',
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
    ]
