# Generated by Django 4.2.5 on 2023-12-23 22:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_user_created_forums_delete_forum'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_opportunities', to=settings.AUTH_USER_MODEL),
        ),
    ]
