# Generated by Django 4.2.5 on 2023-12-23 23:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_opportunity_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='bookmarked_users',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_opportunities_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
