site_name: AVQ Backend

theme:
  name: material
  primary: purple

  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/toggle-switch

  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/toggle-switch-off-outline

    accent: blue

  features:
  - navigation.path
  - navigation.indexes
  - navigation.instant
  - navigation.instant.prefetch
  - navigation.instant.progress
  - navigation.tracking
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - toc.follow
  - toc.integrate

markdown_extensions:
- def_list
- admonition
- pymdownx.details
- pymdownx.superfences

extra_css:
- styles.css
