name: Documentation Build Test

on:
  push:
    branches:
      - main
    paths:
      - 'doc/**'
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install mkdocs
      run: pip install mkdocs

    - name: Build documentation
      run: |
        output=$(mkdocs build 2>&1)

        if echo "$output" | grep -q "WARNING"; then
          echo "Build contains WARNINGs"
          exit 1
        else
          echo "Build completed successfully."
        fi
