name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'doc/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10

    - name: Install mkdocs
      run: pip install mkdocs-material

    - name: Build documentation
      run: mkdocs build
