# Generated by Django 4.2.5 on 2023-11-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_user_created_forums"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
