# Generated by Django 4.2.5 on 2023-11-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_user_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="opp_images/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="user_images/"),
        ),
    ]
