# Generated by Django 4.2.5 on 2023-12-24 17:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_opportunity_profile_image_alter_user_profile_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="waitlist",
            options={"ordering": ["date_created"]},
        ),
    ]
